[Python Documentation](https://docs.python.org/3/library/exceptions.html)
[Re-Raise Exceptions](http://ci1.mle/generic/npapdemo/src/-/pipelines/8580)
## Base Classes
Classes | Description
:--- | :---
BaseException | The base class for all built-in exceptions. It is not meant to be directly inherited by user-defined classes (for that, use [`Exception`](https://docs.python.org/3/library/exceptions.html#Exception "Exception")). If [`str()`](https://docs.python.org/3/library/stdtypes.html#str "str") is called on an instance of this class, the representation of the argument(s) to the instance are returned, or the empty string when there were no arguments.
Exception | All built-in, non-system-exiting exceptions are derived from this class. All user-defined exceptions should also be derived from this class.
ArithmeticError | The base class for those built-in exceptions that are raised for various arithmetic errors: [`OverflowError`](https://docs.python.org/3/library/exceptions.html#OverflowError "OverflowError"), [`ZeroDivisionError`](https://docs.python.org/3/library/exceptions.html#ZeroDivisionError "ZeroDivisionError"), [`FloatingPointError`](https://docs.python.org/3/library/exceptions.html#FloatingPointError "FloatingPointError").
BufferError | Raised when a [buffer](https://docs.python.org/3/c-api/buffer.html#bufferobjects) related operation cannot be performed.
LookupError | The base class for the exceptions that are raised when a key or index used on a mapping or sequence is invalid: [`IndexError`](https://docs.python.org/3/library/exceptions.html#IndexError "IndexError"), [`KeyError`](https://docs.python.org/3/library/exceptions.html#KeyError "KeyError"). This can be raised directly by [`codecs.lookup()`](https://docs.python.org/3/library/codecs.html#codecs.lookup "codecs.lookup").


## Concrete Exceptions

The following exceptions are the exceptions that are usually raised.

Exception | Description
:--- | :---
AssertionError | Raised when an [`assert`](https://docs.python.org/3/reference/simple_stmts.html#assert) statement fails.
AttributeError | when an attribute reference (see [Attribute references](https://docs.python.org/3/reference/expressions.html#attribute-references)) or assignment fails. (When an object does not support attribute references or attribute assignments at all, [`TypeError`](https://docs.python.org/3/library/exceptions.html#TypeError "TypeError") is raised.)
**EOFError** | Raised when the [`input()`](https://docs.python.org/3/library/functions.html#input "input") function hits an end-of-file condition (EOF) without reading any data. (N.B.: the `io.IOBase.read()` and [`io.IOBase.readline()`](https://docs.python.org/3/library/io.html#io.IOBase.readline "io.IOBase.readline") methods return an empty string when they hit EOF.)
FloatingPointError |
GeneratorExit | Raised when a [generator](https://docs.python.org/3/glossary.html#term-generator) or [coroutine](https://docs.python.org/3/glossary.html#term-coroutine) is closed; see [`generator.close()`](https://docs.python.org/3/reference/expressions.html#generator.close "generator.close") and [`coroutine.close()`](https://docs.python.org/3/reference/datamodel.html#coroutine.close "coroutine.close"). It directly inherits from [`BaseException`](https://docs.python.org/3/library/exceptions.html#BaseException "BaseException") instead of [`Exception`](https://docs.python.org/3/library/exceptions.html#Exception "Exception") since it is technically not an error.
ImportError | Raised when the [`import`](https://docs.python.org/3/reference/simple_stmts.html#import) statement has troubles trying to load a module. Also raised when the “from list” in `from ... import` has a name that cannot be found.
ModuleNotFoundError | A subclass of [`ImportError`](https://docs.python.org/3/library/exceptions.html#ImportError "ImportError") which is raised by [`import`](https://docs.python.org/3/reference/simple_stmts.html#import) when a module could not be located. It is also raised when `None` is found in [`sys.modules`](https://docs.python.org/3/library/sys.html#sys.modules "sys.modules").
IndexError | Raised when a sequence subscript is out of range. (Slice indices are silently truncated to fall in the allowed range; if an index is not an integer, [`TypeError`](https://docs.python.org/3/library/exceptions.html#TypeError "TypeError") is raised.)
KeyError | Raised when a mapping (dictionary) key is not found in the set of existing keys.
KeyboardInterrupt | Raised when the user hits the interrupt key (normally Control-C or Delete). During execution, a check for interrupts is made regularly. The exception inherits from [`BaseException`](https://docs.python.org/3/library/exceptions.html#BaseException "BaseException") so as to not be accidentally caught by code that catches [`Exception`](https://docs.python.org/3/library/exceptions.html#Exception "Exception") and thus prevent the interpreter from exiting.
MemoryError | Raised when an operation runs out of memory but the situation may still be rescued (by deleting some objects). The associated value is a string indicating what kind of (internal) operation ran out of memory. Note that because of the underlying memory management architecture (C’s `malloc()` function), the interpreter may not always be able to completely recover from this situation; it nevertheless raises an exception so that a stack traceback can be printed, in case a run-away program was the cause.
NameError | Raised when a local or global name is not found. This applies only to unqualified names. The associated value is an error message that includes the name that could not be found.
NotImplementedError | This exception is derived from [`RuntimeError`](https://docs.python.org/3/library/exceptions.html#RuntimeError "RuntimeError"). In user defined base classes, abstract methods should raise this exception when they require derived classes to override the method, or while the class is being developed to indicate that the real implementation still needs to be added.
OSError([_arg_]) | This exception is raised when a system function returns a system-related error, including I/O failures such as “file not found” or “disk full” (not for illegal argument types or other incidental errors).
OSError(_errno_, _strerror_[, _filename_[, _winerror_[, _filename2_]]]) | 
OverflowError | Raised when the result of an arithmetic operation is too large to be represented. This cannot occur for integers (which would rather raise [`MemoryError`](https://docs.python.org/3/library/exceptions.html#MemoryError "MemoryError") than give up). However, for historical reasons, OverflowError is sometimes raised for integers that are outside a required range. Because of the lack of standardization of floating point exception handling in C, most floating point operations are not checked.
RecursionError | This exception is derived from [`RuntimeError`](https://docs.python.org/3/library/exceptions.html#RuntimeError "RuntimeError"). It is raised when the interpreter detects that the maximum recursion depth (see [`sys.getrecursionlimit()`](https://docs.python.org/3/library/sys.html#sys.getrecursionlimit "sys.getrecursionlimit")) is exceeded.
ReferenceError | This exception is raised when a weak reference proxy, created by the [`weakref.proxy()`](https://docs.python.org/3/library/weakref.html#weakref.proxy "weakref.proxy") function, is used to access an attribute of the referent after it has been garbage collected. For more information on weak references, see the [`weakref`](https://docs.python.org/3/library/weakref.html#module-weakref "weakref: Support for weak references and weak dictionaries.") module.
RuntimeError | Raised when an error is detected that doesn’t fall in any of the other categories. The associated value is a string indicating what precisely went wrong.
StopIteration | Raised by built-in function [`next()`](https://docs.python.org/3/library/functions.html#next "next") and an [iterator](https://docs.python.org/3/glossary.html#term-iterator)'s [`__next__()`](https://docs.python.org/3/library/stdtypes.html#iterator.__next__ "iterator.__next__") method to signal that there are no further items produced by the iterator.
StopAsyncIteration |  Must be raised by `__anext__()` method of an [asynchronous iterator](https://docs.python.org/3/glossary.html#term-asynchronous-iterator) object to stop the iteration.
IndentationError | Base class for syntax errors related to incorrect indentation. This is a subclass of [`SyntaxError`](https://docs.python.org/3/library/exceptions.html#SyntaxError "SyntaxError").
TabError | Raised when indentation contains an inconsistent use of tabs and spaces. This is a subclass of [`IndentationError`](https://docs.python.org/3/library/exceptions.html#IndentationError "IndentationError").
SystemError | Raised when the interpreter finds an internal error, but the situation does not look so serious to cause it to abandon all hope. The associated value is a string indicating what went wrong (in low-level terms).
SystemExit | This exception is raised by the [`sys.exit()`](https://docs.python.org/3/library/sys.html#sys.exit "sys.exit") function. It inherits from [`BaseException`](https://docs.python.org/3/library/exceptions.html#BaseException "BaseException") instead of [`Exception`](https://docs.python.org/3/library/exceptions.html#Exception "Exception") so that it is not accidentally caught by code that catches [`Exception`](https://docs.python.org/3/library/exceptions.html#Exception "Exception"). This allows the exception to properly propagate up and cause the interpreter to exit. When it is not handled, the Python interpreter exits; no stack traceback is printed. The constructor accepts the same optional argument passed to [`sys.exit()`](https://docs.python.org/3/library/sys.html#sys.exit "sys.exit"). If the value is an integer, it specifies the system exit status (passed to C’s `exit()` function); if it is `None`, the exit status is zero; if it has another type (such as a string), the object’s value is printed and the exit status is one.
TypeError | Raised when an operation or function is applied to an object of inappropriate type. The associated value is a string giving details about the type mismatch. This exception may be raised by user code to indicate that an attempted operation on an object is not supported, and is not meant to be. If an object is meant to support a given operation but has not yet provided an implementation, [`NotImplementedError`](https://docs.python.org/3/library/exceptions.html#NotImplementedError "NotImplementedError") is the proper exception to raise.
UnboundLocalError | Raised when a reference is made to a local variable in a function or method, but no value has been bound to that variable. This is a subclass of [`NameError`](https://docs.python.org/3/library/exceptions.html#NameError "NameError").
UnicodeError | Raised when a Unicode-related encoding or decoding error occurs. It is a subclass of [`ValueError`](https://docs.python.org/3/library/exceptions.html#ValueError "ValueError").
UnicodeEncodeError | Raised when a Unicode-related error occurs during encoding. It is a subclass of [`UnicodeError`](https://docs.python.org/3/library/exceptions.html#UnicodeError "UnicodeError").
UnicodeDecodeError | Raised when a Unicode-related error occurs during decoding. It is a subclass of [`UnicodeError`](https://docs.python.org/3/library/exceptions.html#UnicodeError "UnicodeError").
UnicodeTranslateError | Raised when a Unicode-related error occurs during translating. It is a subclass of [`UnicodeError`](https://docs.python.org/3/library/exceptions.html#UnicodeError "UnicodeError").
ValueError | Raised when an operation or function receives an argument that has the right type but an inappropriate value, and the situation is not described by a more precise exception such as [`IndexError`](https://docs.python.org/3/library/exceptions.html#IndexError "IndexError").
ZeroDivisionError | Raised when the second argument of a division or modulo operation is zero. The associated value is a string indicating the type of the operands and the operation.
EnvironmentError | 
IOError | 
WindowsError | Only available on Windows.


## OS Exceptions
The following exceptions are subclasses of [`OSError`](https://docs.python.org/3/library/exceptions.html#OSError "OSError"), they get raised depending on the system error code.

Exception | Description
:--- | :---
BlockingIOError | Raised when an operation would block on an object (e.g. socket) set for non-blocking operation. Corresponds to `errno` [`EAGAIN`](https://docs.python.org/3/library/errno.html#errno.EAGAIN "errno.EAGAIN"), [`EALREADY`](https://docs.python.org/3/library/errno.html#errno.EALREADY "errno.EALREADY"), [`EWOULDBLOCK`](https://docs.python.org/3/library/errno.html#errno.EWOULDBLOCK "errno.EWOULDBLOCK") and [`EINPROGRESS`](https://docs.python.org/3/library/errno.html#errno.EINPROGRESS "errno.EINPROGRESS").
ChildProcessError | Raised when an operation on a child process failed. Corresponds to `errno` [`ECHILD`](https://docs.python.org/3/library/errno.html#errno.ECHILD "errno.ECHILD").
ConnectionError | A base class for connection-related issues. Subclasses are [`BrokenPipeError`](https://docs.python.org/3/library/exceptions.html#BrokenPipeError "BrokenPipeError"), [`ConnectionAbortedError`](https://docs.python.org/3/library/exceptions.html#ConnectionAbortedError "ConnectionAbortedError"), [`ConnectionRefusedError`](https://docs.python.org/3/library/exceptions.html#ConnectionRefusedError "ConnectionRefusedError") and [`ConnectionResetError`](https://docs.python.org/3/library/exceptions.html#ConnectionResetError "ConnectionResetError").
BrokenPipeError | A subclass of [`ConnectionError`](https://docs.python.org/3/library/exceptions.html#ConnectionError "ConnectionError"), raised when trying to write on a pipe while the other end has been closed, or trying to write on a socket which has been shutdown for writing. Corresponds to `errno` [`EPIPE`](https://docs.python.org/3/library/errno.html#errno.EPIPE "errno.EPIPE") and [`ESHUTDOWN`](https://docs.python.org/3/library/errno.html#errno.ESHUTDOWN "errno.ESHUTDOWN").
ConnectionAbortedError | A subclass of [`ConnectionError`](https://docs.python.org/3/library/exceptions.html#ConnectionError "ConnectionError"), raised when a connection attempt is aborted by the peer. Corresponds to `errno` [`ECONNABORTED`](https://docs.python.org/3/library/errno.html#errno.ECONNABORTED "errno.ECONNABORTED").
ConnectionRefusedError | A subclass of [`ConnectionError`](https://docs.python.org/3/library/exceptions.html#ConnectionError "ConnectionError"), raised when a connection attempt is refused by the peer. Corresponds to `errno` [`ECONNREFUSED`](https://docs.python.org/3/library/errno.html#errno.ECONNREFUSED "errno.ECONNREFUSED").
ConnectionResetError | A subclass of [`ConnectionError`](https://docs.python.org/3/library/exceptions.html#ConnectionError "ConnectionError"), raised when a connection is reset by the peer. Corresponds to `errno` [`ECONNRESET`](https://docs.python.org/3/library/errno.html#errno.ECONNRESET "errno.ECONNRESET").
FileExistsError | Raised when trying to create a file or directory which already exists. Corresponds to `errno` [`EEXIST`](https://docs.python.org/3/library/errno.html#errno.EEXIST "errno.EEXIST").
FileNotFoundError | Raised when a file or directory is requested but doesn’t exist. Corresponds to `errno` [`ENOENT`](https://docs.python.org/3/library/errno.html#errno.ENOENT "errno.ENOENT").
InterruptedError | Raised when a system call is interrupted by an incoming signal. Corresponds to `errno` [`EINTR`](https://docs.python.org/3/library/errno.html#errno.EINTR "errno.EINTR").
IsADirectoryError | Raised when a file operation (such as [`os.remove()`](https://docs.python.org/3/library/os.html#os.remove "os.remove")) is requested on a directory. Corresponds to `errno` [`EISDIR`](https://docs.python.org/3/library/errno.html#errno.EISDIR "errno.EISDIR").
NotADirectoryError | Raised when a directory operation (such as [`os.listdir()`](https://docs.python.org/3/library/os.html#os.listdir "os.listdir")) is requested on something which is not a directory. On most POSIX platforms, it may also be raised if an operation attempts to open or traverse a non-directory file as if it were a directory. Corresponds to `errno` [`ENOTDIR`](https://docs.python.org/3/library/errno.html#errno.ENOTDIR "errno.ENOTDIR").
PermissionError | Raised when trying to run an operation without the adequate access rights - for example filesystem permissions. Corresponds to `errno` [`EACCES`](https://docs.python.org/3/library/errno.html#errno.EACCES "errno.EACCES"), [`EPERM`](https://docs.python.org/3/library/errno.html#errno.EPERM "errno.EPERM"), and [`ENOTCAPABLE`](https://docs.python.org/3/library/errno.html#errno.ENOTCAPABLE "errno.ENOTCAPABLE").
ProcessLookupError | Raised when a given process doesn’t exist. Corresponds to `errno` [`ESRCH`](https://docs.python.org/3/library/errno.html#errno.ESRCH "errno.ESRCH").
TimeoutError | Raised when a system function timed out at the system level. Corresponds to `errno` [`ETIMEDOUT`](https://docs.python.org/3/library/errno.html#errno.ETIMEDOUT "errno.ETIMEDOUT").